# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.hostname = "keycloak"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provision :shell, path: "keycloak_install.sh", privileged: false
  # acces au port 1 de la via depuis le port 2 du host
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443, auto_correct: true
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end
  config.vm.synced_folder "./../", "/vagrant"
  #config.vm.provision :shell, path: "keycloak_startup.sh", privileged: false
end
